-- Production data backfill for the canonical permission catalogue.
--
-- Root cause addressed: Permission/RolePermission are data tables, while most
-- permission additions historically lived only in prisma/seed.ts. Production
-- environments that deploy migrations but do not re-run the seed therefore
-- keep an old permission catalogue (for example only 6 ticket permissions).
--
-- Safety:
--   * additive/idempotent by Permission.key and RolePermission PK
--   * existing permission assignments are NEVER deleted
--   * existing role customisations are NEVER re-added for permissions that
--     already existed before this migration
--   * default grants are inserted ONLY for permission keys newly created by
--     this migration, so an admin who intentionally removed an existing grant
--     is not overridden

CREATE TEMP TABLE "_PermissionBackfillInserted" (
  "key" TEXT PRIMARY KEY
);

WITH inserted AS (
  INSERT INTO "Permission" ("id", "key", "description", "module", "createdAt", "updatedAt")
  VALUES
  (gen_random_uuid()::text, 'activity.view', 'View activities', 'activities', now(), now()),
  (gen_random_uuid()::text, 'activity.create', 'Create activities', 'activities', now(), now()),
  (gen_random_uuid()::text, 'activity.edit', 'Edit activities', 'activities', now(), now()),
  (gen_random_uuid()::text, 'activity.delete', 'Delete activities', 'activities', now(), now()),
  (gen_random_uuid()::text, 'activity.assign', 'Assign activities to users', 'activities', now(), now()),
  (gen_random_uuid()::text, 'activity.assignable', 'Can be assigned to activities', 'activities', now(), now()),
  (gen_random_uuid()::text, 'project.view', 'View projects', 'projects', now(), now()),
  (gen_random_uuid()::text, 'project.create', 'Create projects', 'projects', now(), now()),
  (gen_random_uuid()::text, 'project.edit', 'Edit projects', 'projects', now(), now()),
  (gen_random_uuid()::text, 'project.delete', 'Delete projects', 'projects', now(), now()),
  (gen_random_uuid()::text, 'project.assignable', 'Can be assigned to projects', 'projects', now(), now()),
  (gen_random_uuid()::text, 'resourcePlanning.view', 'View the resource planning timeline', 'projects', now(), now()),
  (gen_random_uuid()::text, 'goal.view', 'View yearly goals', 'goals', now(), now()),
  (gen_random_uuid()::text, 'goal.create', 'Create yearly goals', 'goals', now(), now()),
  (gen_random_uuid()::text, 'goal.edit', 'Edit yearly goals', 'goals', now(), now()),
  (gen_random_uuid()::text, 'goal.delete', 'Delete yearly goals', 'goals', now(), now()),
  (gen_random_uuid()::text, 'ticket.view', 'View tickets', 'tickets', now(), now()),
  (gen_random_uuid()::text, 'ticket.create', 'Create tickets', 'tickets', now(), now()),
  (gen_random_uuid()::text, 'ticket.reply', 'Reply to tickets', 'tickets', now(), now()),
  (gen_random_uuid()::text, 'ticket.internalNote', 'Add internal notes', 'tickets', now(), now()),
  (gen_random_uuid()::text, 'ticket.assign', 'Assign tickets to agents', 'tickets', now(), now()),
  (gen_random_uuid()::text, 'ticket.changeStatus', 'Change ticket status', 'tickets', now(), now()),
  (gen_random_uuid()::text, 'ticket.assignable', 'Can be assigned to tickets', 'tickets', now(), now()),
  (gen_random_uuid()::text, 'ticket.department.change', 'Change a ticket''s department/sub-department', 'tickets', now(), now()),
  (gen_random_uuid()::text, 'ticket.share.department', 'Share a ticket with the whole department', 'tickets', now(), now()),
  (gen_random_uuid()::text, 'ticket.share.subdepartment', 'Share a ticket with the whole sub-department', 'tickets', now(), now()),
  (gen_random_uuid()::text, 'ticket.pending.view', 'View pending tickets awaiting review', 'tickets', now(), now()),
  (gen_random_uuid()::text, 'ticket.pending.accept', 'Accept a pending ticket into a real ticket', 'tickets', now(), now()),
  (gen_random_uuid()::text, 'ticket.pending.reject', 'Reject/discard a pending ticket', 'tickets', now(), now()),
  (gen_random_uuid()::text, 'admin.access', 'Access admin panel', 'admin', now(), now()),
  (gen_random_uuid()::text, 'user.manage', 'Manage users', 'admin', now(), now()),
  (gen_random_uuid()::text, 'role.manage', 'Manage roles and permissions', 'admin', now(), now()),
  (gen_random_uuid()::text, 'integration.manage', 'Manage external integrations and their API keys', 'admin', now(), now()),
  (gen_random_uuid()::text, 'department.view', 'View department details', 'department', now(), now()),
  (gen_random_uuid()::text, 'department.manageSettings', 'Edit department settings and categories', 'department', now(), now()),
  (gen_random_uuid()::text, 'department.manageMembers', 'Manage department memberships', 'department', now(), now()),
  (gen_random_uuid()::text, 'department.create', 'Create departments', 'department', now(), now()),
  (gen_random_uuid()::text, 'department.update', 'Edit department settings (structural — name/slug/active)', 'department', now(), now()),
  (gen_random_uuid()::text, 'department.delete', 'Delete or disable departments', 'department', now(), now()),
  (gen_random_uuid()::text, 'company.create', 'Create companies', 'company', now(), now()),
  (gen_random_uuid()::text, 'company.update', 'Edit company name/domain', 'company', now(), now()),
  (gen_random_uuid()::text, 'company.delete', 'Delete a company (only if it has no business units or users)', 'company', now(), now()),
  (gen_random_uuid()::text, 'businessUnit.create', 'Create business units', 'businessUnit', now(), now()),
  (gen_random_uuid()::text, 'businessUnit.update', 'Edit business unit name/company', 'businessUnit', now(), now()),
  (gen_random_uuid()::text, 'businessUnit.delete', 'Delete a business unit (only if it has no departments/users/projects/activities)', 'businessUnit', now(), now()),
  (gen_random_uuid()::text, 'department.user.assign', 'Assign users to a department', 'department', now(), now()),
  (gen_random_uuid()::text, 'department.user.unassign', 'Remove users from a department', 'department', now(), now()),
  (gen_random_uuid()::text, 'department.email.manage', 'Set/change a department''s inbound email address', 'department', now(), now()),
  (gen_random_uuid()::text, 'subdepartment.view', 'View sub-departments', 'subdepartment', now(), now()),
  (gen_random_uuid()::text, 'subdepartment.create', 'Create sub-departments', 'subdepartment', now(), now()),
  (gen_random_uuid()::text, 'subdepartment.update', 'Edit sub-departments', 'subdepartment', now(), now()),
  (gen_random_uuid()::text, 'subdepartment.delete', 'Delete or disable sub-departments', 'subdepartment', now(), now()),
  (gen_random_uuid()::text, 'subdepartment.user.assign', 'Assign users to a sub-department', 'subdepartment', now(), now()),
  (gen_random_uuid()::text, 'subdepartment.user.unassign', 'Remove users from a sub-department', 'subdepartment', now(), now()),
  (gen_random_uuid()::text, 'role.department.create', 'Create department roles', 'admin', now(), now()),
  (gen_random_uuid()::text, 'role.department.update', 'Edit department role permissions', 'admin', now(), now()),
  (gen_random_uuid()::text, 'role.department.delete', 'Delete department roles', 'admin', now(), now()),
  (gen_random_uuid()::text, 'category.manage', 'Create, edit and delete ticket categories', 'ticketConfig', now(), now()),
  (gen_random_uuid()::text, 'category.delete', 'Delete/deactivate ticket categories', 'ticketConfig', now(), now()),
  (gen_random_uuid()::text, 'priority.create', 'Create ticket priorities', 'ticketConfig', now(), now()),
  (gen_random_uuid()::text, 'priority.edit', 'Edit ticket priorities', 'ticketConfig', now(), now()),
  (gen_random_uuid()::text, 'priority.delete', 'Delete/deactivate ticket priorities', 'ticketConfig', now(), now()),
  (gen_random_uuid()::text, 'status.create', 'Create ticket statuses', 'ticketConfig', now(), now()),
  (gen_random_uuid()::text, 'status.edit', 'Edit ticket statuses', 'ticketConfig', now(), now()),
  (gen_random_uuid()::text, 'status.delete', 'Delete/deactivate ticket statuses', 'ticketConfig', now(), now()),
  (gen_random_uuid()::text, 'cancelReason.create', 'Create ticket cancel reasons', 'ticketConfig', now(), now()),
  (gen_random_uuid()::text, 'cancelReason.edit', 'Edit ticket cancel reasons', 'ticketConfig', now(), now()),
  (gen_random_uuid()::text, 'cancelReason.delete', 'Delete/deactivate ticket cancel reasons', 'ticketConfig', now(), now()),
  (gen_random_uuid()::text, 'sla.create', 'Create a department''s SLA policy for a priority', 'ticketConfig', now(), now()),
  (gen_random_uuid()::text, 'sla.edit', 'Edit SLA response/resolution hours', 'ticketConfig', now(), now()),
  (gen_random_uuid()::text, 'sla.delete', 'Remove a department''s SLA policy override', 'ticketConfig', now(), now()),
  (gen_random_uuid()::text, 'activityProgress.create', 'Add a status row to this department''s activity progress mapping', 'ticketConfig', now(), now()),
  (gen_random_uuid()::text, 'activityProgress.edit', 'Edit this department''s status->progress% mapping for activities', 'ticketConfig', now(), now()),
  (gen_random_uuid()::text, 'activityProgress.delete', 'Remove a status row from this department''s activity progress mapping', 'ticketConfig', now(), now()),
  (gen_random_uuid()::text, 'organization.sync', 'Trigger a full/incremental Microsoft organization sync', 'organization', now(), now()),
  (gen_random_uuid()::text, 'organization.tree.view', 'View the full organization department/people tree (beyond one''s own slice)', 'organization', now(), now())
  ON CONFLICT ("key") DO NOTHING
  RETURNING "key"
)
INSERT INTO "_PermissionBackfillInserted" ("key")
SELECT "key" FROM inserted;

-- Keep the system-owned catalogue metadata aligned with the current source.
UPDATE "Permission" AS p
SET
  "description" = v."description",
  "module" = v."module",
  "updatedAt" = now()
FROM (
  VALUES
    ('activity.view', 'View activities', 'activities'),
    ('activity.create', 'Create activities', 'activities'),
    ('activity.edit', 'Edit activities', 'activities'),
    ('activity.delete', 'Delete activities', 'activities'),
    ('activity.assign', 'Assign activities to users', 'activities'),
    ('activity.assignable', 'Can be assigned to activities', 'activities'),
    ('project.view', 'View projects', 'projects'),
    ('project.create', 'Create projects', 'projects'),
    ('project.edit', 'Edit projects', 'projects'),
    ('project.delete', 'Delete projects', 'projects'),
    ('project.assignable', 'Can be assigned to projects', 'projects'),
    ('resourcePlanning.view', 'View the resource planning timeline', 'projects'),
    ('goal.view', 'View yearly goals', 'goals'),
    ('goal.create', 'Create yearly goals', 'goals'),
    ('goal.edit', 'Edit yearly goals', 'goals'),
    ('goal.delete', 'Delete yearly goals', 'goals'),
    ('ticket.view', 'View tickets', 'tickets'),
    ('ticket.create', 'Create tickets', 'tickets'),
    ('ticket.reply', 'Reply to tickets', 'tickets'),
    ('ticket.internalNote', 'Add internal notes', 'tickets'),
    ('ticket.assign', 'Assign tickets to agents', 'tickets'),
    ('ticket.changeStatus', 'Change ticket status', 'tickets'),
    ('ticket.assignable', 'Can be assigned to tickets', 'tickets'),
    ('ticket.department.change', 'Change a ticket''s department/sub-department', 'tickets'),
    ('ticket.share.department', 'Share a ticket with the whole department', 'tickets'),
    ('ticket.share.subdepartment', 'Share a ticket with the whole sub-department', 'tickets'),
    ('ticket.pending.view', 'View pending tickets awaiting review', 'tickets'),
    ('ticket.pending.accept', 'Accept a pending ticket into a real ticket', 'tickets'),
    ('ticket.pending.reject', 'Reject/discard a pending ticket', 'tickets'),
    ('admin.access', 'Access admin panel', 'admin'),
    ('user.manage', 'Manage users', 'admin'),
    ('role.manage', 'Manage roles and permissions', 'admin'),
    ('integration.manage', 'Manage external integrations and their API keys', 'admin'),
    ('department.view', 'View department details', 'department'),
    ('department.manageSettings', 'Edit department settings and categories', 'department'),
    ('department.manageMembers', 'Manage department memberships', 'department'),
    ('department.create', 'Create departments', 'department'),
    ('department.update', 'Edit department settings (structural — name/slug/active)', 'department'),
    ('department.delete', 'Delete or disable departments', 'department'),
    ('company.create', 'Create companies', 'company'),
    ('company.update', 'Edit company name/domain', 'company'),
    ('company.delete', 'Delete a company (only if it has no business units or users)', 'company'),
    ('businessUnit.create', 'Create business units', 'businessUnit'),
    ('businessUnit.update', 'Edit business unit name/company', 'businessUnit'),
    ('businessUnit.delete', 'Delete a business unit (only if it has no departments/users/projects/activities)', 'businessUnit'),
    ('department.user.assign', 'Assign users to a department', 'department'),
    ('department.user.unassign', 'Remove users from a department', 'department'),
    ('department.email.manage', 'Set/change a department''s inbound email address', 'department'),
    ('subdepartment.view', 'View sub-departments', 'subdepartment'),
    ('subdepartment.create', 'Create sub-departments', 'subdepartment'),
    ('subdepartment.update', 'Edit sub-departments', 'subdepartment'),
    ('subdepartment.delete', 'Delete or disable sub-departments', 'subdepartment'),
    ('subdepartment.user.assign', 'Assign users to a sub-department', 'subdepartment'),
    ('subdepartment.user.unassign', 'Remove users from a sub-department', 'subdepartment'),
    ('role.department.create', 'Create department roles', 'admin'),
    ('role.department.update', 'Edit department role permissions', 'admin'),
    ('role.department.delete', 'Delete department roles', 'admin'),
    ('category.manage', 'Create, edit and delete ticket categories', 'ticketConfig'),
    ('category.delete', 'Delete/deactivate ticket categories', 'ticketConfig'),
    ('priority.create', 'Create ticket priorities', 'ticketConfig'),
    ('priority.edit', 'Edit ticket priorities', 'ticketConfig'),
    ('priority.delete', 'Delete/deactivate ticket priorities', 'ticketConfig'),
    ('status.create', 'Create ticket statuses', 'ticketConfig'),
    ('status.edit', 'Edit ticket statuses', 'ticketConfig'),
    ('status.delete', 'Delete/deactivate ticket statuses', 'ticketConfig'),
    ('cancelReason.create', 'Create ticket cancel reasons', 'ticketConfig'),
    ('cancelReason.edit', 'Edit ticket cancel reasons', 'ticketConfig'),
    ('cancelReason.delete', 'Delete/deactivate ticket cancel reasons', 'ticketConfig'),
    ('sla.create', 'Create a department''s SLA policy for a priority', 'ticketConfig'),
    ('sla.edit', 'Edit SLA response/resolution hours', 'ticketConfig'),
    ('sla.delete', 'Remove a department''s SLA policy override', 'ticketConfig'),
    ('activityProgress.create', 'Add a status row to this department''s activity progress mapping', 'ticketConfig'),
    ('activityProgress.edit', 'Edit this department''s status->progress% mapping for activities', 'ticketConfig'),
    ('activityProgress.delete', 'Remove a status row from this department''s activity progress mapping', 'ticketConfig'),
    ('organization.sync', 'Trigger a full/incremental Microsoft organization sync', 'organization'),
    ('organization.tree.view', 'View the full organization department/people tree (beyond one''s own slice)', 'organization')
) AS v("key", "description", "module")
WHERE p."key" = v."key"
  AND (p."description" IS DISTINCT FROM v."description" OR p."module" IS DISTINCT FROM v."module");

-- Fresh-install defaults, but ONLY for permission rows that were genuinely
-- absent before this migration. This preserves any prior admin customisation
-- of permissions that already existed in production.
WITH default_grants("roleKey", "permissionKey") AS (
  VALUES
    ('ADMIN', 'activity.view'),
    ('ADMIN', 'activity.create'),
    ('ADMIN', 'activity.edit'),
    ('ADMIN', 'activity.delete'),
    ('ADMIN', 'activity.assign'),
    ('ADMIN', 'activity.assignable'),
    ('ADMIN', 'project.view'),
    ('ADMIN', 'project.create'),
    ('ADMIN', 'project.edit'),
    ('ADMIN', 'project.delete'),
    ('ADMIN', 'project.assignable'),
    ('ADMIN', 'resourcePlanning.view'),
    ('ADMIN', 'goal.view'),
    ('ADMIN', 'goal.create'),
    ('ADMIN', 'goal.edit'),
    ('ADMIN', 'goal.delete'),
    ('ADMIN', 'ticket.view'),
    ('ADMIN', 'ticket.create'),
    ('ADMIN', 'ticket.reply'),
    ('ADMIN', 'ticket.internalNote'),
    ('ADMIN', 'ticket.assign'),
    ('ADMIN', 'ticket.changeStatus'),
    ('ADMIN', 'ticket.assignable'),
    ('ADMIN', 'ticket.department.change'),
    ('ADMIN', 'ticket.share.department'),
    ('ADMIN', 'ticket.share.subdepartment'),
    ('ADMIN', 'ticket.pending.view'),
    ('ADMIN', 'ticket.pending.accept'),
    ('ADMIN', 'ticket.pending.reject'),
    ('ADMIN', 'admin.access'),
    ('ADMIN', 'user.manage'),
    ('ADMIN', 'role.manage'),
    ('ADMIN', 'integration.manage'),
    ('ADMIN', 'department.view'),
    ('ADMIN', 'department.manageSettings'),
    ('ADMIN', 'department.manageMembers'),
    ('ADMIN', 'department.create'),
    ('ADMIN', 'department.update'),
    ('ADMIN', 'department.delete'),
    ('ADMIN', 'company.create'),
    ('ADMIN', 'company.update'),
    ('ADMIN', 'company.delete'),
    ('ADMIN', 'businessUnit.create'),
    ('ADMIN', 'businessUnit.update'),
    ('ADMIN', 'businessUnit.delete'),
    ('ADMIN', 'department.user.assign'),
    ('ADMIN', 'department.user.unassign'),
    ('ADMIN', 'department.email.manage'),
    ('ADMIN', 'subdepartment.view'),
    ('ADMIN', 'subdepartment.create'),
    ('ADMIN', 'subdepartment.update'),
    ('ADMIN', 'subdepartment.delete'),
    ('ADMIN', 'subdepartment.user.assign'),
    ('ADMIN', 'subdepartment.user.unassign'),
    ('ADMIN', 'role.department.create'),
    ('ADMIN', 'role.department.update'),
    ('ADMIN', 'role.department.delete'),
    ('ADMIN', 'category.manage'),
    ('ADMIN', 'category.delete'),
    ('ADMIN', 'priority.create'),
    ('ADMIN', 'priority.edit'),
    ('ADMIN', 'priority.delete'),
    ('ADMIN', 'status.create'),
    ('ADMIN', 'status.edit'),
    ('ADMIN', 'status.delete'),
    ('ADMIN', 'cancelReason.create'),
    ('ADMIN', 'cancelReason.edit'),
    ('ADMIN', 'cancelReason.delete'),
    ('ADMIN', 'sla.create'),
    ('ADMIN', 'sla.edit'),
    ('ADMIN', 'sla.delete'),
    ('ADMIN', 'activityProgress.create'),
    ('ADMIN', 'activityProgress.edit'),
    ('ADMIN', 'activityProgress.delete'),
    ('ADMIN', 'organization.sync'),
    ('ADMIN', 'organization.tree.view'),
    ('IT_AGENT', 'activity.view'),
    ('IT_AGENT', 'activity.create'),
    ('IT_AGENT', 'activity.edit'),
    ('IT_AGENT', 'activity.assign'),
    ('IT_AGENT', 'activity.assignable'),
    ('IT_AGENT', 'project.view'),
    ('IT_AGENT', 'project.create'),
    ('IT_AGENT', 'project.edit'),
    ('IT_AGENT', 'resourcePlanning.view'),
    ('IT_AGENT', 'goal.view'),
    ('IT_AGENT', 'ticket.view'),
    ('IT_AGENT', 'ticket.create'),
    ('IT_AGENT', 'ticket.reply'),
    ('IT_AGENT', 'ticket.internalNote'),
    ('IT_AGENT', 'ticket.assign'),
    ('IT_AGENT', 'ticket.changeStatus'),
    ('IT_AGENT', 'ticket.assignable'),
    ('IT_AGENT', 'ticket.share.department'),
    ('IT_AGENT', 'ticket.share.subdepartment'),
    ('IT_AGENT', 'ticket.pending.view'),
    ('IT_AGENT', 'ticket.pending.accept'),
    ('DEPARTMENT_MANAGER', 'activity.view'),
    ('DEPARTMENT_MANAGER', 'activity.create'),
    ('DEPARTMENT_MANAGER', 'activity.edit'),
    ('DEPARTMENT_MANAGER', 'activity.assign'),
    ('DEPARTMENT_MANAGER', 'activity.assignable'),
    ('DEPARTMENT_MANAGER', 'project.view'),
    ('DEPARTMENT_MANAGER', 'project.create'),
    ('DEPARTMENT_MANAGER', 'project.edit'),
    ('DEPARTMENT_MANAGER', 'project.assignable'),
    ('DEPARTMENT_MANAGER', 'resourcePlanning.view'),
    ('DEPARTMENT_MANAGER', 'goal.view'),
    ('DEPARTMENT_MANAGER', 'goal.create'),
    ('DEPARTMENT_MANAGER', 'goal.edit'),
    ('DEPARTMENT_MANAGER', 'ticket.view'),
    ('DEPARTMENT_MANAGER', 'ticket.create'),
    ('DEPARTMENT_MANAGER', 'ticket.reply'),
    ('DEPARTMENT_MANAGER', 'ticket.assignable'),
    ('DEPARTMENT_MANAGER', 'ticket.department.change'),
    ('DEPARTMENT_MANAGER', 'ticket.share.department'),
    ('DEPARTMENT_MANAGER', 'ticket.share.subdepartment'),
    ('DEPARTMENT_MANAGER', 'department.view'),
    ('DEPARTMENT_MANAGER', 'department.user.assign'),
    ('DEPARTMENT_MANAGER', 'department.user.unassign'),
    ('DEPARTMENT_MANAGER', 'department.email.manage'),
    ('DEPARTMENT_MANAGER', 'subdepartment.view'),
    ('DEPARTMENT_MANAGER', 'subdepartment.create'),
    ('DEPARTMENT_MANAGER', 'subdepartment.update'),
    ('DEPARTMENT_MANAGER', 'subdepartment.delete'),
    ('DEPARTMENT_MANAGER', 'subdepartment.user.assign'),
    ('DEPARTMENT_MANAGER', 'subdepartment.user.unassign'),
    ('DEPARTMENT_MANAGER', 'ticket.pending.view'),
    ('DEPARTMENT_MANAGER', 'ticket.pending.accept'),
    ('DEPARTMENT_MANAGER', 'ticket.pending.reject'),
    ('DEPARTMENT_MANAGER', 'category.manage'),
    ('DEPARTMENT_MANAGER', 'category.delete'),
    ('DEPARTMENT_MANAGER', 'priority.create'),
    ('DEPARTMENT_MANAGER', 'priority.edit'),
    ('DEPARTMENT_MANAGER', 'priority.delete'),
    ('DEPARTMENT_MANAGER', 'status.create'),
    ('DEPARTMENT_MANAGER', 'status.edit'),
    ('DEPARTMENT_MANAGER', 'status.delete'),
    ('DEPARTMENT_MANAGER', 'cancelReason.create'),
    ('DEPARTMENT_MANAGER', 'cancelReason.edit'),
    ('DEPARTMENT_MANAGER', 'cancelReason.delete'),
    ('DEPARTMENT_MANAGER', 'sla.create'),
    ('DEPARTMENT_MANAGER', 'sla.edit'),
    ('DEPARTMENT_MANAGER', 'sla.delete'),
    ('DEPARTMENT_MANAGER', 'activityProgress.create'),
    ('DEPARTMENT_MANAGER', 'activityProgress.edit'),
    ('DEPARTMENT_MANAGER', 'activityProgress.delete'),
    ('USER', 'activity.view'),
    ('USER', 'ticket.view'),
    ('USER', 'ticket.create'),
    ('USER', 'ticket.reply'),
    ('DIRECTOR', 'ticket.view'),
    ('DIRECTOR', 'project.view'),
    ('DIRECTOR', 'project.create'),
    ('DIRECTOR', 'resourcePlanning.view'),
    ('DIRECTOR', 'activity.view'),
    ('DIRECTOR', 'activity.create'),
    ('DIRECTOR', 'goal.view'),
    ('DIRECTOR', 'department.view'),
    ('DIRECTOR', 'subdepartment.view'),
    ('DIRECTOR', 'ticket.pending.view'),
    ('DIRECTOR', 'organization.tree.view'),
    ('DEPARTMENT_ADMIN', 'activity.view'),
    ('DEPARTMENT_ADMIN', 'activity.create'),
    ('DEPARTMENT_ADMIN', 'activity.edit'),
    ('DEPARTMENT_ADMIN', 'activity.delete'),
    ('DEPARTMENT_ADMIN', 'activity.assign'),
    ('DEPARTMENT_ADMIN', 'activity.assignable'),
    ('DEPARTMENT_ADMIN', 'project.view'),
    ('DEPARTMENT_ADMIN', 'project.create'),
    ('DEPARTMENT_ADMIN', 'project.edit'),
    ('DEPARTMENT_ADMIN', 'project.delete'),
    ('DEPARTMENT_ADMIN', 'project.assignable'),
    ('DEPARTMENT_ADMIN', 'resourcePlanning.view'),
    ('DEPARTMENT_ADMIN', 'goal.view'),
    ('DEPARTMENT_ADMIN', 'goal.create'),
    ('DEPARTMENT_ADMIN', 'goal.edit'),
    ('DEPARTMENT_ADMIN', 'goal.delete'),
    ('DEPARTMENT_ADMIN', 'ticket.view'),
    ('DEPARTMENT_ADMIN', 'ticket.create'),
    ('DEPARTMENT_ADMIN', 'ticket.reply'),
    ('DEPARTMENT_ADMIN', 'ticket.internalNote'),
    ('DEPARTMENT_ADMIN', 'ticket.assign'),
    ('DEPARTMENT_ADMIN', 'ticket.changeStatus'),
    ('DEPARTMENT_ADMIN', 'ticket.assignable'),
    ('DEPARTMENT_ADMIN', 'ticket.department.change'),
    ('DEPARTMENT_ADMIN', 'ticket.share.department'),
    ('DEPARTMENT_ADMIN', 'ticket.share.subdepartment'),
    ('DEPARTMENT_ADMIN', 'department.view'),
    ('DEPARTMENT_ADMIN', 'department.manageSettings'),
    ('DEPARTMENT_ADMIN', 'department.manageMembers'),
    ('DEPARTMENT_ADMIN', 'department.email.manage'),
    ('DEPARTMENT_ADMIN', 'department.user.assign'),
    ('DEPARTMENT_ADMIN', 'department.user.unassign'),
    ('DEPARTMENT_ADMIN', 'subdepartment.view'),
    ('DEPARTMENT_ADMIN', 'subdepartment.create'),
    ('DEPARTMENT_ADMIN', 'subdepartment.update'),
    ('DEPARTMENT_ADMIN', 'subdepartment.delete'),
    ('DEPARTMENT_ADMIN', 'subdepartment.user.assign'),
    ('DEPARTMENT_ADMIN', 'subdepartment.user.unassign'),
    ('DEPARTMENT_ADMIN', 'ticket.pending.view'),
    ('DEPARTMENT_ADMIN', 'ticket.pending.accept'),
    ('DEPARTMENT_ADMIN', 'ticket.pending.reject'),
    ('DEPARTMENT_ADMIN', 'category.manage'),
    ('DEPARTMENT_ADMIN', 'category.delete'),
    ('DEPARTMENT_ADMIN', 'priority.create'),
    ('DEPARTMENT_ADMIN', 'priority.edit'),
    ('DEPARTMENT_ADMIN', 'priority.delete'),
    ('DEPARTMENT_ADMIN', 'status.create'),
    ('DEPARTMENT_ADMIN', 'status.edit'),
    ('DEPARTMENT_ADMIN', 'status.delete'),
    ('DEPARTMENT_ADMIN', 'cancelReason.create'),
    ('DEPARTMENT_ADMIN', 'cancelReason.edit'),
    ('DEPARTMENT_ADMIN', 'cancelReason.delete'),
    ('DEPARTMENT_ADMIN', 'sla.create'),
    ('DEPARTMENT_ADMIN', 'sla.edit'),
    ('DEPARTMENT_ADMIN', 'sla.delete'),
    ('DEPARTMENT_ADMIN', 'activityProgress.create'),
    ('DEPARTMENT_ADMIN', 'activityProgress.edit'),
    ('DEPARTMENT_ADMIN', 'activityProgress.delete'),
    ('PROJECT_MANAGER', 'activity.view'),
    ('PROJECT_MANAGER', 'activity.create'),
    ('PROJECT_MANAGER', 'activity.edit'),
    ('PROJECT_MANAGER', 'activity.assign'),
    ('PROJECT_MANAGER', 'activity.assignable'),
    ('PROJECT_MANAGER', 'project.view'),
    ('PROJECT_MANAGER', 'project.create'),
    ('PROJECT_MANAGER', 'project.edit'),
    ('PROJECT_MANAGER', 'project.assignable'),
    ('PROJECT_MANAGER', 'resourcePlanning.view'),
    ('PROJECT_MANAGER', 'goal.view'),
    ('AGENT_ASSIGNEE', 'activity.view'),
    ('AGENT_ASSIGNEE', 'activity.edit'),
    ('AGENT_ASSIGNEE', 'activity.assignable'),
    ('AGENT_ASSIGNEE', 'project.view'),
    ('AGENT_ASSIGNEE', 'resourcePlanning.view'),
    ('AGENT_ASSIGNEE', 'ticket.view'),
    ('AGENT_ASSIGNEE', 'ticket.create'),
    ('AGENT_ASSIGNEE', 'ticket.reply'),
    ('AGENT_ASSIGNEE', 'ticket.internalNote'),
    ('AGENT_ASSIGNEE', 'ticket.assign'),
    ('AGENT_ASSIGNEE', 'ticket.changeStatus'),
    ('AGENT_ASSIGNEE', 'ticket.assignable'),
    ('AGENT_ASSIGNEE', 'ticket.share.department'),
    ('AGENT_ASSIGNEE', 'ticket.share.subdepartment'),
    ('AGENT_ASSIGNEE', 'ticket.pending.view'),
    ('AGENT_ASSIGNEE', 'ticket.pending.accept'),
    ('REQUESTER', 'activity.view'),
    ('REQUESTER', 'ticket.view'),
    ('REQUESTER', 'ticket.create'),
    ('REQUESTER', 'ticket.reply'),
    ('VIEWER', 'activity.view'),
    ('VIEWER', 'project.view'),
    ('VIEWER', 'goal.view'),
    ('VIEWER', 'ticket.view')
)
INSERT INTO "RolePermission" ("roleKey", "permissionId", "createdAt")
SELECT dg."roleKey", p."id", now()
FROM default_grants dg
JOIN "_PermissionBackfillInserted" i ON i."key" = dg."permissionKey"
JOIN "Permission" p ON p."key" = dg."permissionKey"
ON CONFLICT ("roleKey", "permissionId") DO NOTHING;

DROP TABLE "_PermissionBackfillInserted";